# Generated by comic_git_engine. Do not edit.
{{ backend }}
{{ publish_mode }}media_folder: "your_content/images"
public_folder: "/your_content/images"
editor:
  preview: false
collections:
{{ comic_settings_collection }}
{{ collections }}
