<!doctype html>
<!-- Generated by comic_git_engine. Do not edit. -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex, nofollow">
    <title>Comic Content Manager</title>
    <link rel="stylesheet" href="../comic_git_engine/css/cms.css">
    {%- if theme_stylesheet_url %}
    <link rel="stylesheet" href="{{ theme_stylesheet_url | e }}">
    {%- endif %}
  </head>
  <body>
    <!-- Register engine widgets before Decap reads config.yml. -->
    <script>window.CMS_MANUAL_INIT = true;</script>
    <script src="{{ decap_cms_url }}"></script>
    <script src="../comic_git_engine/js/cms_widgets.js"></script>
    <script>window.initCMS();</script>
  </body>
</html>
