name: Build Site

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4

      - name: Switch to master branch (or create it)
        run: git checkout -B master

      - name: Reset master to match working
        run: |
          git fetch --depth 1 --no-tags origin working
          git reset --hard origin/working
          git status

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Pull in comic_git_engine
        run: |
          ENGINE_VERSION=$(sed -n 's/Engine version = \(.*\)/\1/p' your_content/comic_info.ini)
          echo "Engine version: $ENGINE_VERSION"
          git submodule add -b "$ENGINE_VERSION" -f https://github.com/ryanvilbrandt/comic_git_engine

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r comic_git_engine/scripts/requirements.txt
          python comic_git_engine/scripts/make_requirements_hooks_file.py
          pip install -r comic_git_engine/scripts/requirements_hooks.txt

      - name: Run python build script
        run: |
          python comic_git_engine/scripts/build_site.py --delete-scheduled-posts
          python_exit_code=$?
          echo "python script exit code: $python_exit_code"
          if [ $python_exit_code -ne 0 ]; then
            exit $python_exit_code
          fi

      - name: Commit files
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add --all
          git diff-index --quiet HEAD || git commit -m "Auto-build"

      - name: Push changes
        run: |
          git push -f --set-upstream origin master
