on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New script version'
        required: true


jobs:
  Update Version and Build Branches:
    runs-on: ubuntu-latest
    steps:
      - name: Load repository
        uses: actions/checkout@v2
      - name: Update "latest" branch
        run: |
          git fetch --all
          git checkout latest
          git reset --hard origin/master
          git push -f
      - name: Update minor version branch
        run: |
          export INPUT=${{ github.event.inputs.version }}
          export ENGINE_VERSION=$(echo $INPUT | sed 's/\.[^.]*$//')
          echo "Engine version (minor only): $ENGINE_VERSION"
          git checkout -b $ENGINE_VERSION
          git reset --hard origin/master
          git push -f --set-upstream origin $ENGINE_VERSION
      - name: Update revision branch
        run: |
          export ENGINE_VERSION=${{ github.event.inputs.version }}
          echo "Engine version (full): $ENGINE_VERSION"
          git checkout -b $ENGINE_VERSION
          git reset --hard origin/master
          git tag v$ENGINE_VERSION
          git push -f --tag --set-upstream origin $ENGINE_VERSION
