on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New script version'
        required: true


jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Load repository
        uses: actions/checkout@v2
      - name: Update version in build_site.py
        run: |
          sed -i 's/VERSION = ".*"/VERSION = "${{ github.event.inputs.version }}"/' scripts/build_site.py
          git config --local user.name "Github Action"
          git config --local user.email "action@github.com"
          git add --all
          git commit -m "Version ${{ github.event.inputs.version }}"
          git push
      - name: Update "latest" branch
        run: |
          git fetch --all
          git checkout latest
          git reset --hard origin/master
          git push -f
      - name: Update minor version branch
        run: |
          export INPUT=${{ github.event.inputs.version }}
          export ENGINE_VERSION=$(echo $INPUT | sed 's/\.[^.]*$//')
          echo "Engine version (minor only): $ENGINE_VERSION"
          git checkout -b $ENGINE_VERSION
          git reset --hard origin/master
          git push -f --set-upstream origin $ENGINE_VERSION
      - name: Update revision branch
        run: |
          export ENGINE_VERSION=${{ github.event.inputs.version }}
          echo "Engine version (full): $ENGINE_VERSION"
          git checkout -b $ENGINE_VERSION
          git reset --hard origin/master
          git tag v$ENGINE_VERSION
          git push -f --tag --set-upstream origin $ENGINE_VERSION

  make_release:
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 2 | tail -n 1)
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT
      - name: Get commits since previous tag
        id: changelog
        run: |
          PREV_TAG="${{ steps.prev_tag.outputs.prev_tag }}"
          NEW_TAG="v${{ github.event.inputs.version }}"
          if [ -z "$PREV_TAG" ]; then
            RANGE=""
          else
            RANGE="$PREV_TAG..HEAD"
          fi
          COMMITS=$(git log $RANGE --pretty=format:'* [%s](https://github.com/${{ github.repository }}/commit/%H)' --no-merges)
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create release notes
        id: notes
        run: |
          NEW_TAG="v${{ github.event.inputs.version }}"
          PREV_TAG="${{ steps.prev_tag.outputs.prev_tag }}"
          echo "## What's New" > release.md
          echo "" >> release.md
          echo "${{ steps.changelog.outputs.commits }}" >> release.md
          echo "" >> release.md
          echo "" >> release.md
          echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREV_TAG...$NEW_TAG" >> release.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body_path: release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
