on:
  workflow_dispatch:
    branches:
      - working


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load repository
        uses: actions/checkout@v2
      - name: Update "latest" branch
        run: |
          git fetch --all
          git checkout latest
#          git reset --hard origin/master
          git merge master
          git push -f
      - name: Update revision branch
        run: |
          export ENGINE_VERSION=$(sed -n 's/VERSION = "\(.*\..*\..*\)"/\1/p' scripts/build_site.py)
          echo "Engine version: $ENGINE_VERSION"
          git checkout -b $ENGINE_VERSION
#          git reset --hard origin/master
          git merge master
          git push -f --set-upstream origin $ENGINE_VERSION
      - name: Update minor version branch
        run: |
          export ENGINE_VERSION=$(sed -n 's/VERSION = "\(.*\..*\)\..*"/\1/p' scripts/build_site.py)
          echo "Engine version: $ENGINE_VERSION"
          git checkout -b $ENGINE_VERSION
#          git reset --hard origin/master
          git merge master
          git push -f --set-upstream origin $ENGINE_VERSION
#      - name: Run python build script
#        run: |
#          python comic_git_engine/scripts/build_site.py --delete-scheduled-posts
#      - name: Commit files
#        run: |
#          git config --local user.name "Github Action"
#          git config --local user.email "action@github.com"
#          git add --all
#          git diff-index --quiet HEAD || git commit -m "Auto-build"
#      - name: Push changes
#        run: |
#          git push -f --set-upstream origin master
