import ast
import argparse
import importlib.util
import os
import re
import subprocess
import sys
import tempfile
import textwrap
from types import ModuleType
from unittest import TestCase
from unittest.mock import MagicMock, patch


ENGINE_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD_SITE = os.path.join(ENGINE_ROOT, "src", "build", "build_site.py")
MIGRATE_TO_TOML = os.path.join(ENGINE_ROOT, "src", "build", "migrate_to_toml.py")
DELETE_AUTOGENERATED = os.path.join(ENGINE_ROOT, "src", "scripts", "delete_autogenerated_files.py")
MAKE_REQUIREMENTS = os.path.join(ENGINE_ROOT, "src", "scripts", "make_requirements_hooks_file.py")
DEV_SERVER = os.path.join(ENGINE_ROOT, "src", "scripts", "dev_server.py")
BUILD_SITE_WORKFLOW = os.path.join(ENGINE_ROOT, ".github", "workflows", "build_site.yaml")
RELEASE_WORKFLOW = os.path.join(ENGINE_ROOT, ".github", "workflows", "main.yaml")


class TestEntrypoints(TestCase):

    def run_entrypoint(self, script_path: str, *args: str) -> subprocess.CompletedProcess[str]:
        env = os.environ.copy()
        env.pop("PYTHONPATH", None)
        with tempfile.TemporaryDirectory() as temp_dir:
            return subprocess.run(
                [sys.executable, script_path, *args],
                cwd=temp_dir,
                capture_output=True,
                text=True,
                env=env,
            )

    def test_build_site_can_be_run_directly_by_path(self):
        result = self.run_entrypoint(BUILD_SITE, "--help")

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertIn("--output-dir", result.stdout)
        self.assertIn("--cms-local-backend", result.stdout)

    def test_migrate_to_toml_can_be_run_directly_by_path(self):
        result = self.run_entrypoint(MIGRATE_TO_TOML, "--help")

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertIn("--write", result.stdout)
        self.assertIn("--delete-legacy", result.stdout)
        self.assertIn("config", result.stdout)

    def test_delete_autogenerated_files_imports_cleanly_when_run_by_path(self):
        result = self.run_entrypoint(DELETE_AUTOGENERATED)
        combined_output = result.stdout + result.stderr

        self.assertNotEqual(0, result.returncode)
        self.assertNotIn("ModuleNotFoundError", combined_output)
        self.assertIn("Couldn't find a folder", combined_output)

    def test_make_requirements_hooks_file_imports_cleanly_when_run_by_path(self):
        result = self.run_entrypoint(MAKE_REQUIREMENTS)
        combined_output = result.stdout + result.stderr

        self.assertNotEqual(0, result.returncode)
        self.assertNotIn("ModuleNotFoundError", combined_output)
        self.assertIn("Couldn't find a folder", combined_output)

    def test_make_requirements_hooks_file_prefers_toml_config(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            os.makedirs(os.path.join(temp_dir, "comic_git_engine"))
            toml_theme_dir = os.path.join(
                temp_dir,
                "your_content",
                "themes",
                "toml-theme",
                "scripts",
            )
            ini_theme_dir = os.path.join(
                temp_dir,
                "your_content",
                "themes",
                "ini-theme",
                "scripts",
            )
            os.makedirs(toml_theme_dir)
            os.makedirs(ini_theme_dir)
            with open(os.path.join(temp_dir, "your_content", "comic_info.toml"), "w", encoding="utf-8") as f:
                f.write('[site]\ntheme = "toml-theme"\n')
            with open(os.path.join(temp_dir, "your_content", "comic_info.ini"), "w", encoding="utf-8") as f:
                f.write("[Comic Settings]\nTheme = ini-theme\n")
            with open(os.path.join(toml_theme_dir, "requirements.txt"), "w", encoding="utf-8") as f:
                f.write("toml-package\n")
            with open(os.path.join(ini_theme_dir, "requirements.txt"), "w", encoding="utf-8") as f:
                f.write("ini-package\n")

            result = subprocess.run(
                [sys.executable, MAKE_REQUIREMENTS],
                cwd=temp_dir,
                capture_output=True,
                text=True,
            )

            self.assertEqual(0, result.returncode, msg=result.stderr)
            with open(
                    os.path.join(temp_dir, "comic_git_engine", "requirements_hooks.txt"),
                    encoding="utf-8",
            ) as f:
                self.assertEqual("toml-package", f.read())

    def test_dev_server_watches_toml_files(self):
        with open(DEV_SERVER, "r", encoding="utf-8") as f:
            module = ast.parse(f.read())
        watch_extensions = next(
            ast.literal_eval(node.value)
            for node in module.body
            if isinstance(node, ast.Assign)
            and any(
                isinstance(target, ast.Name) and target.id == "WATCH_EXTENSIONS"
                for target in node.targets
            )
        )

        self.assertIn(".toml", watch_extensions)

    def test_dev_server_uses_discovered_host_root_and_toml_loader(self):
        watchdog = ModuleType("watchdog")
        observers = ModuleType("watchdog.observers")
        events = ModuleType("watchdog.events")
        observers.Observer = MagicMock
        events.FileSystemEventHandler = object
        spec = importlib.util.spec_from_file_location("test_dev_server_module", DEV_SERVER)
        module = importlib.util.module_from_spec(spec)
        observer = MagicMock()
        thread = MagicMock()
        args = argparse.Namespace(
            delete_scheduled_posts=False,
            publish_all_comics=False,
            output_dir=None,
            cms_local_backend=True,
        )
        comic_info = object()

        with (
            patch.dict(sys.modules, {
                "watchdog": watchdog,
                "watchdog.observers": observers,
                "watchdog.events": events,
            }),
            tempfile.TemporaryDirectory() as temp_dir,
        ):
            cwd = os.getcwd()
            try:
                os.chdir(temp_dir)
                spec.loader.exec_module(module)
                with (
                    patch.object(module.utils, "find_project_root"),
                    patch.object(module.build_site, "parse_args", return_value=args),
                    patch.object(module.build_site, "apply_cli_environment_overrides") as mock_apply_overrides,
                    patch.object(module, "load_main_comic_info", return_value=comic_info) as mock_load_config,
                    patch.object(module.utils, "get_comic_url", return_value=("https://example.com/comic", "/comic")),
                    patch.object(module.utils, "get_output_dir", return_value="build"),
                    patch.object(module.build_site, "main") as mock_build,
                    patch.object(module, "watch_and_rebuild", return_value=observer) as mock_watch,
                    patch.object(module.threading, "Thread", return_value=thread),
                    patch.object(module, "start_http_server"),
                    patch.object(module, "delete_output_file_space") as mock_delete_output,
                ):
                    module.main()

                request_handler = object.__new__(module.PreviewRequestHandler)
                request_handler.directory = module.HTTP_ROOT
                translated_path = request_handler.translate_path("/comic/comic/001/")
            finally:
                os.chdir(cwd)

        self.assertEqual(temp_dir, module.PROJECT_ROOT)
        self.assertEqual(os.path.join(temp_dir, "build"), module.HTTP_ROOT)
        self.assertEqual("/comic", module.PREVIEW_SUBDIRECTORY)
        mock_load_config.assert_called_once_with()
        mock_apply_overrides.assert_called_once_with(args)
        mock_build.assert_called_once_with(False, False, True)
        mock_watch.assert_called_once_with([False, False, True])
        thread.start.assert_called_once_with()
        mock_delete_output.assert_called_once_with(comic_info)
        self.assertEqual(
            os.path.normpath(os.path.join(temp_dir, "build", "comic", "001")),
            os.path.normpath(translated_path),
        )


class TestWorkflowEntrypoints(TestCase):

    def read_build_workflow(self) -> str:
        with open(BUILD_SITE_WORKFLOW, "r", encoding="utf-8") as f:
            return f.read()

    def read_release_workflow(self) -> str:
        with open(RELEASE_WORKFLOW, "r", encoding="utf-8") as f:
            return f.read()

    def extract_engine_version_script(self) -> str:
        workflow = self.read_build_workflow()
        match = re.search(r"ENGINE_VERSION=\$\(python - <<'PY'\n(?P<script>.*?)\n\s*PY", workflow, re.DOTALL)
        self.assertIsNotNone(match)
        return textwrap.dedent(match.group("script"))

    def test_build_workflow_preserves_output_directory_across_artifact_jobs(self):
        workflow = self.read_build_workflow()
        download_paths = re.findall(
            r"- name: Download build artifact\s+"
            r"uses: actions/download-artifact@v4\s+"
            r"with:\s+name: site\s+path: (.+)",
            workflow,
        )

        self.assertEqual(["${{ inputs.OUTPUT_DIR || '.' }}"] * 2, download_paths)
        self.assertIn("dist_dir: ${{ inputs.OUTPUT_DIR || '.' }}", workflow)

    def run_engine_version_script(self, fixture_files: dict[str, str]) -> subprocess.CompletedProcess[str]:
        script = self.extract_engine_version_script()
        with tempfile.TemporaryDirectory() as temp_dir:
            for relative_path, content in fixture_files.items():
                path = os.path.join(temp_dir, relative_path)
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
            return subprocess.run(
                [sys.executable, "-c", script],
                cwd=temp_dir,
                capture_output=True,
                text=True,
            )

    def test_build_workflow_reads_engine_version_from_toml(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": '[engine]\nversion = "1.2"\n',
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.2", result.stdout.strip())

    def test_build_workflow_prefers_toml_engine_version_over_ini(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": '[engine]\nversion = "1.2"\n',
            "your_content/comic_info.ini": "[Comic Settings]\nEngine version = 1.3\n",
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.2", result.stdout.strip())

    def test_build_workflow_rejects_non_table_engine_toml_value(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": 'engine = "1.2"\n',
        })

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Expected engine in comic_info.toml to be a table", result.stderr)

    def test_build_workflow_rejects_non_string_engine_version_toml_value(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": "[engine]\nversion = 1.2\n",
        })

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Expected engine.version in comic_info.toml to be a string", result.stderr)

    def test_build_workflow_reads_engine_version_from_ini(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.ini": "[Comic Settings]\nEngine version = 1.3\n",
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.3", result.stdout.strip())

    def test_build_workflow_defaults_engine_version_when_toml_omits_it(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": "[comic]\nname = \"No Engine Version\"\n",
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.1", result.stdout.strip())

    def test_build_workflow_fails_when_config_file_is_missing(self):
        result = self.run_engine_version_script({})

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Expected your_content/comic_info.toml or your_content/comic_info.ini", result.stderr)

    def test_release_workflow_updates_build_workflow_engine_version_fallback(self):
        workflow = self.read_release_workflow()

        self.assertIn('echo "minor_version=$MAJOR.$MINOR"', workflow)
        self.assertIn("MINOR_VERSION: ${{ needs.validate_release.outputs.minor_version }}", workflow)
        self.assertIn('DEFAULT_ENGINE_VERSION = \\"$MINOR_VERSION\\"', workflow)

    def test_release_workflow_accepts_only_complete_canonical_versions(self):
        workflow = self.read_release_workflow()
        match = re.search(
            r'if \[\[ ! "\$RELEASE_VERSION" =~ (?P<pattern>\^.*\$) \]\]; then',
            workflow,
        )
        self.assertIsNotNone(match)
        version_pattern = re.compile(match.group("pattern"))

        for version in ("0.0.0", "1.1.0", "12.34.567"):
            with self.subTest(version=version):
                self.assertIsNotNone(version_pattern.fullmatch(version))

        for version in ("1.1", "v1.1.0", "1.1.0-beta", "01.1.0", "1.01.0", "1.1.00", "1;echo bad"):
            with self.subTest(version=version):
                self.assertIsNone(version_pattern.fullmatch(version))

        self.assertIn('DISPATCH_REF: ${{ github.ref }}', workflow)
        self.assertIn('if [[ "$DISPATCH_REF" != "refs/heads/master" ]]', workflow)
        self.assertLess(workflow.index("validate_release:"), workflow.index("update_version:"))

    def test_release_workflow_rejects_existing_exact_refs_before_mutation(self):
        workflow = self.read_release_workflow()
        validate_refs = workflow.index("- name: Validate exact refs and capture master")
        update_version = workflow.index("  update_version:")

        self.assertLess(validate_refs, update_version)
        self.assertGreaterEqual(
            workflow.count('git ls-remote --exit-code --heads origin "refs/heads/$RELEASE_VERSION"'),
            2,
        )
        self.assertGreaterEqual(
            workflow.count('git ls-remote --exit-code --tags origin "refs/tags/v$RELEASE_VERSION"'),
            2,
        )
        self.assertIn("already exists and is immutable", workflow)
        self.assertIn("appeared after validation; refusing to move it", workflow)

    def test_release_workflow_rejects_overlap_and_stale_master(self):
        workflow = self.read_release_workflow()

        self.assertIn("actions/github-script@v7", workflow)
        self.assertIn("github.rest.actions.listWorkflowRuns", workflow)
        self.assertIn("run.id < context.runId", workflow)
        self.assertIn("active release run", workflow)
        self.assertIn("group: comic-git-engine-release-mutation", workflow)
        self.assertIn("cancel-in-progress: false", workflow)
        self.assertIn("queue: max", workflow)
        self.assertIn("EXPECTED_MASTER_SHA: ${{ needs.validate_release.outputs.master_sha }}", workflow)
        self.assertIn('if [[ "$CURRENT_MASTER_SHA" != "$EXPECTED_MASTER_SHA" ]]', workflow)
        self.assertIn("Review the new repository state and dispatch a new release run.", workflow)

    def test_release_workflow_manages_minor_and_exact_refs_but_not_major_tags(self):
        workflow = self.read_release_workflow()

        self.assertNotIn("MAJOR_TAG", workflow)
        self.assertNotIn("git push --delete", workflow)
        self.assertIn('MINOR_TAG="v$MINOR_VERSION"', workflow)
        self.assertIn('FULL_TAG="v$RELEASE_VERSION"', workflow)
        self.assertIn('git branch -f "$MINOR_VERSION"', workflow)
        self.assertIn('git tag -f "$MINOR_TAG"', workflow)
        self.assertIn('git branch "$RELEASE_VERSION"', workflow)
        self.assertNotIn('git branch -f "$RELEASE_VERSION"', workflow)
        self.assertIn('git tag "$FULL_TAG"', workflow)
        self.assertNotIn('git tag -f "$FULL_TAG"', workflow)
        self.assertNotIn('git push --force origin "refs/tags/$FULL_TAG"', workflow)

    def test_release_workflow_uses_scoped_permissions_safe_reruns_and_draft_release(self):
        workflow = self.read_release_workflow()

        self.assertIn("actions: read\n      contents: read", workflow)
        self.assertEqual(2, workflow.count("contents: write"))
        self.assertIn("if git diff --cached --quiet; then", workflow)
        self.assertIn("reusing the existing master commit", workflow)
        self.assertIn("- name: Create draft GitHub Release", workflow)
        self.assertIn("draft: true", workflow)
