import ast
import os
import re
import subprocess
import sys
import tempfile
import textwrap
from unittest import TestCase


ENGINE_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD_SITE = os.path.join(ENGINE_ROOT, "src", "build", "build_site.py")
MIGRATE_TO_TOML = os.path.join(ENGINE_ROOT, "src", "build", "migrate_to_toml.py")
DELETE_AUTOGENERATED = os.path.join(ENGINE_ROOT, "src", "scripts", "delete_autogenerated_files.py")
MAKE_REQUIREMENTS = os.path.join(ENGINE_ROOT, "src", "scripts", "make_requirements_hooks_file.py")
DEV_SERVER = os.path.join(ENGINE_ROOT, "src", "scripts", "dev_server.py")
BUILD_SITE_WORKFLOW = os.path.join(ENGINE_ROOT, ".github", "workflows", "build_site.yaml")
RELEASE_WORKFLOW = os.path.join(ENGINE_ROOT, ".github", "workflows", "main.yaml")


class TestEntrypoints(TestCase):

    def run_entrypoint(self, script_path: str, *args: str) -> subprocess.CompletedProcess[str]:
        env = os.environ.copy()
        env.pop("PYTHONPATH", None)
        with tempfile.TemporaryDirectory() as temp_dir:
            return subprocess.run(
                [sys.executable, script_path, *args],
                cwd=temp_dir,
                capture_output=True,
                text=True,
                env=env,
            )

    def test_build_site_can_be_run_directly_by_path(self):
        result = self.run_entrypoint(BUILD_SITE, "--help")

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertIn("--output-dir", result.stdout)

    def test_migrate_to_toml_can_be_run_directly_by_path(self):
        result = self.run_entrypoint(MIGRATE_TO_TOML, "--help")

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertIn("--write", result.stdout)
        self.assertIn("--delete-legacy", result.stdout)
        self.assertIn("config", result.stdout)

    def test_delete_autogenerated_files_imports_cleanly_when_run_by_path(self):
        result = self.run_entrypoint(DELETE_AUTOGENERATED)
        combined_output = result.stdout + result.stderr

        self.assertNotEqual(0, result.returncode)
        self.assertNotIn("ModuleNotFoundError", combined_output)
        self.assertIn("Couldn't find a folder", combined_output)

    def test_make_requirements_hooks_file_imports_cleanly_when_run_by_path(self):
        result = self.run_entrypoint(MAKE_REQUIREMENTS)
        combined_output = result.stdout + result.stderr

        self.assertNotEqual(0, result.returncode)
        self.assertNotIn("ModuleNotFoundError", combined_output)
        self.assertIn("Couldn't find a folder", combined_output)

    def test_dev_server_watches_toml_files(self):
        with open(DEV_SERVER, "r", encoding="utf-8") as f:
            module = ast.parse(f.read())
        watch_extensions = next(
            ast.literal_eval(node.value)
            for node in module.body
            if isinstance(node, ast.Assign)
            and any(
                isinstance(target, ast.Name) and target.id == "WATCH_EXTENSIONS"
                for target in node.targets
            )
        )

        self.assertIn(".toml", watch_extensions)


class TestWorkflowEntrypoints(TestCase):

    def extract_engine_version_script(self) -> str:
        with open(BUILD_SITE_WORKFLOW, "r", encoding="utf-8") as f:
            workflow = f.read()
        match = re.search(r"ENGINE_VERSION=\$\(python - <<'PY'\n(?P<script>.*?)\n\s*PY", workflow, re.DOTALL)
        self.assertIsNotNone(match)
        return textwrap.dedent(match.group("script"))

    def run_engine_version_script(self, fixture_files: dict[str, str]) -> subprocess.CompletedProcess[str]:
        script = self.extract_engine_version_script()
        with tempfile.TemporaryDirectory() as temp_dir:
            for relative_path, content in fixture_files.items():
                path = os.path.join(temp_dir, relative_path)
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "w", encoding="utf-8") as f:
                    f.write(content)
            return subprocess.run(
                [sys.executable, "-c", script],
                cwd=temp_dir,
                capture_output=True,
                text=True,
            )

    def test_build_workflow_reads_engine_version_from_toml(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": '[engine]\nversion = "1.2"\n',
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.2", result.stdout.strip())

    def test_build_workflow_prefers_toml_engine_version_over_ini(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": '[engine]\nversion = "1.2"\n',
            "your_content/comic_info.ini": "[Comic Settings]\nEngine version = 1.3\n",
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.2", result.stdout.strip())

    def test_build_workflow_rejects_non_table_engine_toml_value(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": 'engine = "1.2"\n',
        })

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Expected engine in comic_info.toml to be a table", result.stderr)

    def test_build_workflow_rejects_non_string_engine_version_toml_value(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": "[engine]\nversion = 1.2\n",
        })

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Expected engine.version in comic_info.toml to be a string", result.stderr)

    def test_build_workflow_reads_engine_version_from_ini(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.ini": "[Comic Settings]\nEngine version = 1.3\n",
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.3", result.stdout.strip())

    def test_build_workflow_defaults_engine_version_when_toml_omits_it(self):
        result = self.run_engine_version_script({
            "your_content/comic_info.toml": "[comic]\nname = \"No Engine Version\"\n",
        })

        self.assertEqual(0, result.returncode, msg=result.stderr)
        self.assertEqual("1.1", result.stdout.strip())

    def test_build_workflow_fails_when_config_file_is_missing(self):
        result = self.run_engine_version_script({})

        self.assertNotEqual(0, result.returncode)
        self.assertIn("Expected your_content/comic_info.toml or your_content/comic_info.ini", result.stderr)

    def test_release_workflow_updates_build_workflow_engine_version_fallback(self):
        with open(RELEASE_WORKFLOW, "r", encoding="utf-8") as f:
            workflow = f.read()

        self.assertIn("MAJOR=$(echo $VERSION | cut -d. -f1)", workflow)
        self.assertIn("MINOR=$(echo $VERSION | cut -d. -f2)", workflow)
        self.assertIn('DEFAULT_ENGINE_VERSION = \\"$MAJOR.$MINOR\\"', workflow)
